version: '3'
services:
  mysql:
    image: 'joseihf/rpi-mysql-moodle:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle
    volumes:
      - 'mysql:/var/lib/mysql'
      - 'mysql_conf:/etc/mysql'
  moodle:
    image: 'treehouses/moodle:rpi-latest'
    ports:
      - '80:80'
    environment:
      - MOODOLE_DB_URL=mysql
      - MOODOLE_DB_NAME=moodle
      - MOODOLE_DB_USER=moodle
      - MOODOLE_DB_PASS=moodle
      - MOODOLE_DB_PORT=3306
    volumes:
      - 'moodle:/var/www/'
    depends_on:
      - mysql
volumes:
  mysql:
    driver: local
  mysql_conf:
    driver: local
  moodle:
    driver: local

